export { default as Header } from "./header/Header.astro";
export { default as Hero } from "./hero/Hero.astro";
export { default as LoveStory } from "./love-story/LoveStory.astro";
export { default as Timeline } from "./timeline/Timeline.astro";
export { default as WeddingDetails } from "./details/WeddingDetails.astro";
export { default as DayTimeline } from "./day-timeline/DayTimeline.astro";
export { default as ImportantInfo } from "./info/ImportantInfo.astro";
export { default as WeddingParty } from "./wedding-party/WeddingParty.astro";
export { default as Registry } from "./registry/Registry.astro";